### ISSUE TITLE
next-dev.js?3515:20 Warning: Extra attributes from the server:

### ISSUE THREAD

**Issue by sytpb** [mAAdhaTTah/babel-plugin-prismjs#325]
i got the warning . 
next-dev.js?3515:20 Warning: Extra attributes from the server: class,tabindex
    at pre
    at div
    at main
    at div
    at div
    at Home (webpack-internal:///./pages/index.js:54:52)
    at MyApp (webpack-internal:///./pages/_app.js:18:24)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:8:20740)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:8:23547)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:82:1)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:529:3)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:671:3)

    "babel-plugin-prismjs": "^2.1.0",
    "next": "12.2.4",
    "prismjs": "^1.28.0",
    "react": "18.2.0",

.babelrc 

{
    "presets": ["next/babel"],
    "plugins": [
      [
        "prismjs",
        {
          "languages": ["javascript", "css", "markup"],
          "plugins": ["line-numbers"],
          "theme": "twilight",
          "css": true
        }
      ]
    ]
}

**Comment by mAAdhaTTah** [comment]
This is unlikely to be caused by the babel plugin but I need a reproduction of the issue before I can determine that.
